version: "3.3"
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    command: "mkdocs serve -a 0.0.0.0:8000"
    ports:
      - $DOCS_PORT:8000
    volumes: 
      - .:/home/mkdocs
